### ISSUE TITLE
train the skin disease dataset

### ISSUE THREAD

**Issue by TWENTY-FOU** [mindflow-institue/TransCeption#3]
Hello dear author, how does your model train the skin disease dataset? Can you show me the code you used to train the skin disease dataset? I am a student from Yunnan University, and your code is only for learning! Thank you very much

**Comment by amirhossein-kz** [comment]
Hi @TWENTY-FOU,
Sorry for the long delay. You can have access to the training code for the skin dataset in [DeformableLKA](https://github.com/mindflow-institue/deformableLKA/tree/main/2D) and [TransNorm](https://github.com/rezazad68/transnorm). You may find it helpful.
